### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by TomaszMachnik** [dreamcodestudio/com.dreamcode.mobile.easy-share#1]
Hi,
I've just bought the Easy Share plugin. How can I install Samples? The folder is gray out on Unity 2021 and 2023.
![Zrzut ekranu 2024-11-12 135355](https://github.com/user-attachments/assets/ff49df0c-bdda-43f8-aa1b-5f9cb1de19f6)

**Comment by yapetrichka** [comment]
Hi you need open `Package Manager` and find `Easy Share` Samples tab
![image](https://github.com/user-attachments/assets/44a508a0-6dfc-4f63-9a1c-2e029fbf257e)

**Comment by TomaszMachnik** [comment]
Thanks, works great.
