### ISSUE TITLE
iOS documentation

### ISSUE THREAD

**Issue by TomaszMachnik** [dreamcodestudio/com.dreamcode.mobile.easy-share#2]
Did you manage to add iOS to the documentation? You wrote about it a month ago on Unity asset store's plugin page.

**Comment by yapetrichka** [comment]
It's on Asset Store review, i notify, when docs approved

**Comment by yapetrichka** [comment]
if you have some problems you can direct message in tg channel:
https://t.me/dreamcestudio/13

**Comment by TomaszMachnik** [comment]
And could you make ready-to-use iOS sample scene/code and share it?
I can send you my invoice to proof I'm a legit user of your plugin.

**Comment by yapetrichka** [comment]
> And could you make ready-to-use iOS sample scene/code and share it? I can send you my invoice to proof I'm a legit user of your plugin.

it's crossplatform solution code similar between Android and iOS platform

**Comment by yapetrichka** [comment]
you try `Text` example on iOS it's worked?

**Comment by TomaszMachnik** [comment]
Yep, it's working for screenshot but we had to install NativeGallery plugin, too.

**Comment by yapetrichka** [comment]
> Yep, it's working for screenshot but we had to install NativeGallery plugin, too.

but plugin not implements Screenshot function, it's designed to Share functionality, for Screenshots and can use any solutions: Unity or third party library
